// Writes src/components/icons.tsx: the site's Phosphor icons, bold weight only.
//
//   node scripts/icons.mjs
//
// Each @phosphor-icons/react component carries all six weights (about 5x the
// bytes the site uses, a fifth of the whole bundle), while the site only ever
// draws bold. This copies each icon's bold paths into a small component under
// the name the pages already import. Add an icon: put it in ICONS and re-run.
import { readFileSync, writeFileSync } from "node:fs";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";

/** Name the pages use -> Phosphor's name. */
const ICONS = {
  Archive: "Archive", ArrowLeft: "ArrowLeft", ArrowUpRight: "ArrowUpRight", Ban: "Prohibit", Bell: "Bell",
  BellOff: "BellSlash", BellRing: "BellRinging", BookOpen: "BookOpen", CalendarClock: "CalendarDots", Check: "Check",
  ChevronDown: "CaretDown", ChevronLeft: "CaretLeft", ChevronRight: "CaretRight", ChevronUp: "CaretUp",
  CircleAlert: "WarningCircle", CircleCheck: "CheckCircle", CircleDot: "Record", Clapperboard: "FilmSlate",
  Clock: "Clock", Clock3: "Clock", Coffee: "Coffee", Copy: "Copy", Download: "DownloadSimple", Eye: "Eye",
  Flame: "Fire", FolderInput: "TrayArrowDown", GitFork: "GitFork", Headphones: "Headphones", Heart: "Heart",
  Hourglass: "Hourglass", House: "House", Inbox: "Tray", Library: "Books", LifeBuoy: "Lifebuoy", Link2: "Link",
  ListOrdered: "ListNumbers", Lock: "Lock", LogOut: "SignOut", Mail: "Envelope", MessageCircle: "ChatCircle",
  MessageSquare: "ChatText", MonitorPlay: "MonitorPlay", PackageOpen: "Package", Play: "Play", PlayCircle: "PlayCircle",
  Pause: "Pause", Plus: "Plus", Power: "Power", Radio: "Broadcast", RefreshCw: "ArrowsClockwise", Search: "MagnifyingGlass",
  Settings: "GearSix", Share: "Export", Share2: "ShareNetwork", ShieldCheck: "ShieldCheck", SquarePlus: "PlusSquare",
  Star: "Star", Ticket: "Ticket", Trash2: "Trash", Tv: "Television", UserPlus: "UserPlus", X: "X",
};

const defs = new URL("../node_modules/@phosphor-icons/react/dist/defs/", import.meta.url);
const body = {};
for (const source of new Set(Object.values(ICONS))) {
  const { default: weights } = await import(new URL(`${source}.es.js`, defs));
  body[source] = renderToStaticMarkup(createElement("svg", null, weights.get("bold"))).replace(/^<svg>|<\/svg>$/g, "");
}

const version = JSON.parse(readFileSync(new URL("../node_modules/@phosphor-icons/react/package.json", import.meta.url))).version;
const lines = [
  "// Generated by scripts/icons.mjs from @phosphor-icons/react " + version + " (MIT): bold weight only.",
  "// Don't edit by hand; add the icon to the script and re-run it.",
  'import { forwardRef, type SVGProps } from "react";',
  "",
  "type IconProps = Omit<SVGProps<SVGSVGElement>, \"ref\"> & { size?: number | string; color?: string };",
  "export type Icon = ReturnType<typeof icon>;",
  "",
  "function icon(name: string, paths: string) {",
  "  const Component = forwardRef<SVGSVGElement, IconProps>(({ size = 24, color = \"currentColor\", ...rest }, ref) => (",
  "    <svg ref={ref} xmlns=\"http://www.w3.org/2000/svg\" width={size} height={size} fill={color} viewBox=\"0 0 256 256\"",
  "      {...rest} dangerouslySetInnerHTML={{ __html: paths }} />",
  "  ));",
  "  Component.displayName = name;",
  "  return Component;",
  "}",
  "",
  ...Object.entries(body).map(([source, svg]) => `const ${source}Bold = ${JSON.stringify(svg)};`),
  "",
  ...Object.entries(ICONS).map(([name, source]) => `export const ${name} = icon(${JSON.stringify(name)}, ${source}Bold);`),
  "",
];
writeFileSync(new URL("../src/components/icons.tsx", import.meta.url), lines.join("\n"));
console.log(`icons.tsx: ${Object.keys(ICONS).length} icons from ${Object.keys(body).length} Phosphor glyphs`);
